package com.heymeowcat.tailznet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

/**
 *
 * @author HEYMEOWCAT
 */
public class SendingEmail {

    private String useremail;
    private String userhash;
    private String msg;

    public SendingEmail(String useremail, String userhash) {
        this.useremail = useremail;
        this.userhash = userhash;
    }

    public void sendMail() {
        final String email = "tailz.network@gmail.com";
        final String password = "vidura2531";
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com"); //SMTP Host
        props.put("mail.smtp.port", "587"); //TLS Port
        props.put("mail.smtp.auth", "true"); //enable authentication
        props.put("mail.smtp.starttls.enable", "true"); //enable STARTTLS

        //create Authenticator object to pass in Session.getInstance argument
        Authenticator auth = new Authenticator() {
            //override the getPasswordAuthentication method
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(email, password);
            }
        };
        Session session = Session.getInstance(props, auth);

        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(email));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(useremail));

            message.setSubject("Taiz | Email Verification Link");
            message.setText("Verification Link  ");
            message.setText("https://tailznet.herokuapp.com/ActivateAccount?key1=" + useremail + "&key2=" + userhash);
            Multipart mp = new MimeMultipart();
            MimeBodyPart htmlPart = new MimeBodyPart();
            String html = "<!DOCTYPE html>\n"
                    + "<html lang=\"en\">\n"
                    + "\n"
                    + "<head>\n"
                    + "  <meta charset=\"UTF-8\">\n"
                    + "  <title>Tailz Verification</title>\n"
                    + "</head>\n"
                    + "\n"
                    + "<body>\n"
                    + "\n"
                    + "  <head>\n"
                    + "    <title>Tailz Verification</title>\n"
                    + "    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\n"
                    + "    <meta http-equiv=\"x-ua-compatible\" content=\"IE=edge\">\n"
                    + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                    + "    <meta name=\"format-detection\" content=\"telephone=no\">\n"
                    + "    <!--[if !mso]><!-->\n"
                    + "    <link\n"
                    + "      href=\"https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i\"\n"
                    + "      rel=\"stylesheet\">\n"
                    + "    <!--<![endif]-->\n"
                    + "    <!--[if gte mso 9]>\n"
                    + "    <xml>\n"
                    + "      <o:OfficeDocumentSettings>\n"
                    + "        <o:AllowPNG />\n"
                    + "        <o:PixelsPerInch>96</o:PixelsPerInch>\n"
                    + "      </o:OfficeDocumentSettings>\n"
                    + "    </xml>\n"
                    + "    <![endif]-->\n"
                    + "\n"
                    + "    <style type=\"text/css\">\n"
                    + "      body {\n"
                    + "        margin: 0 !important;\n"
                    + "        padding: 0 !important;\n"
                    + "        -webkit-text-size-adjust: 100% !important;\n"
                    + "        -ms-text-size-adjust: 100% !important;\n"
                    + "        -webkit-font-smoothing: antialiased !important;\n"
                    + "      }\n"
                    + "\n"
                    + "      img {\n"
                    + "        border: 0 !important;\n"
                    + "        outline: none !important;\n"
                    + "      }\n"
                    + "\n"
                    + "      p {\n"
                    + "        margin: 0 !important;\n"
                    + "        padding: 0 !important;\n"
                    + "      }\n"
                    + "\n"
                    + "      table {\n"
                    + "        border-collapse: collapse;\n"
                    + "        mso-table-lspace: 0;\n"
                    + "        mso-table-rspace: 0;\n"
                    + "      }\n"
                    + "\n"
                    + "      td,\n"
                    + "      a,\n"
                    + "      span {\n"
                    + "        border-collapse: collapse;\n"
                    + "        mso-line-height-rule: exactly;\n"
                    + "      }\n"
                    + "\n"
                    + "      .ExternalClass * {\n"
                    + "        line-height: 100%;\n"
                    + "      }\n"
                    + "\n"
                    + "      .em_defaultlink a {\n"
                    + "        color: inherit !important;\n"
                    + "        text-decoration: none !important;\n"
                    + "      }\n"
                    + "\n"
                    + "      span.MsoHyperlink {\n"
                    + "        mso-style-priority: 99;\n"
                    + "        color: inherit;\n"
                    + "      }\n"
                    + "\n"
                    + "      span.MsoHyperlinkFollowed {\n"
                    + "        mso-style-priority: 99;\n"
                    + "        color: inherit;\n"
                    + "      }\n"
                    + "\n"
                    + "      .em_footer a {\n"
                    + "        color: #6b6b6b;\n"
                    + "        text-decoration: none;\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_main_table {\n"
                    + "          width: 100% !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_wrapper {\n"
                    + "          width: 100% !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_side {\n"
                    + "          width: 10px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_hide {\n"
                    + "          display: none !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_height {\n"
                    + "          height: 20px !important;\n"
                    + "          font-size: 1px !important;\n"
                    + "          line-height: 1px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_height2 {\n"
                    + "          height: 50px !important;\n"
                    + "          font-size: 1px !important;\n"
                    + "          line-height: 1px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_height3 {\n"
                    + "          height: 30px !important;\n"
                    + "          font-size: 1px !important;\n"
                    + "          line-height: 1px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_height4 {\n"
                    + "          height: 90px !important;\n"
                    + "          font-size: 1px !important;\n"
                    + "          line-height: 1px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_bg {\n"
                    + "          height: auto !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media only screen and (min-width:481px) and (max-width:799px) {\n"
                    + "        .em_full_img {\n"
                    + "          width: 100% !important;\n"
                    + "          height: auto !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_main_table {\n"
                    + "          width: 100% !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_wrapper {\n"
                    + "          width: 100% !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_side {\n"
                    + "          width: 10px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_hide {\n"
                    + "          display: none !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_height {\n"
                    + "          height: 20px !important;\n"
                    + "          font-size: 1px !important;\n"
                    + "          line-height: 1px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_height2 {\n"
                    + "          height: 50px !important;\n"
                    + "          font-size: 1px !important;\n"
                    + "          line-height: 1px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_height4 {\n"
                    + "          height: 50px !important;\n"
                    + "          font-size: 1px !important;\n"
                    + "          line-height: 1px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_height3 {\n"
                    + "          height: 30px !important;\n"
                    + "          font-size: 1px !important;\n"
                    + "          line-height: 1px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        u+.em_body .em_full_wrap {\n"
                    + "          width: 100vw !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_txt1 {\n"
                    + "          font-size: 40px !important;\n"
                    + "          line-height: 42px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_txt2 {\n"
                    + "          font-size: 13px !important;\n"
                    + "          line-height: 20px !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_bg {\n"
                    + "          height: auto !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_full_img {\n"
                    + "          width: 100% !important;\n"
                    + "          height: auto !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "\n"
                    + "      @media screen and (max-width: 480px) {\n"
                    + "        .em_img1 {\n"
                    + "          width: 190px !important;\n"
                    + "          height: auto !important;\n"
                    + "          max-width: none !important;\n"
                    + "        }\n"
                    + "\n"
                    + "      }\n"
                    + "    </style>\n"
                    + "  </head>\n"
                    + "\n"
                    + "  <body class=\"em_body\"\n"
                    + "    style=\"margin: 0px;padding: 0px;-webkit-text-size-adjust: 100% !important;-ms-text-size-adjust: 100% !important;-webkit-font-smoothing: antialiased !important;\"\n"
                    + "    bgcolor=\"#ffffff\">\n"
                    + "    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"em_full_wrap\" bgcolor=\"#ffffff\"\n"
                    + "      style=\"border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\">\n"
                    + "      <tbody>\n"
                    + "        <tr>\n"
                    + "          <td align=\"center\" valign=\"top\" bgcolor=\"#ffffff\"\n"
                    + "            style=\"border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "            <table align=\"center\" width=\"800\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"em_main_table\"\n"
                    + "              style=\"width: 800px;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\" bgcolor=\"#000000\">\n"
                    + "              <tbody>\n"
                    + "                <tr>\n"
                    + "                  <td class=\"em_bg\" align=\"center\" valign=\"top\" background=\"https://i.imgur.com/oK5iMjY.jpg\" height=\"585\"\n"
                    + "                    style=\"background-repeat: no-repeat;background-position: center top;background-size: 100%;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                    <!--[if gte mso 9]>\n"
                    + "                <v:rect xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"true\" stroke=\"false\" style=\"width:800px;height:585px;\">\n"
                    + "                  <v:fill type=\"tile\" src=\"https://i.imgur.com/oK5iMjY.jpg\" color=\"#000000\" />\n"
                    + "                  <v:textbox inset=\"0,0,0,0\">\n"
                    + "                    <![endif]-->\n"
                    + "\n"
                    + "                    <table align=\"center\" width=\"800\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"em_wrapper\"\n"
                    + "                      style=\"width: 800px;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\">\n"
                    + "                      <tbody>\n"
                    + "                        <tr>\n"
                    + "                          <td width=\"90\" class=\"em_side\"\n"
                    + "                            style=\"width: 90px;border-collapse: collapse;mso-line-height-rule: exactly;\">&nbsp;</td>\n"
                    + "                          <td align=\"center\" valign=\"top\"\n"
                    + "                            style=\"border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                            <table align=\"center\" width=\"620\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                              class=\"em_wrapper\"\n"
                    + "                              style=\"width: 620px;border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\">\n"
                    + "                              <tbody>\n"
                    + "                                <tr>\n"
                    + "                                  <td height=\"58\"\n"
                    + "                                    style=\"height: 58px;border-collapse: collapse;mso-line-height-rule: exactly;\"\n"
                    + "                                    class=\"em_height\">&nbsp;</td>\n"
                    + "                                </tr>\n"
                    + "\n"
                    + "                                <tr>\n"
                    + "                                  <td height=\"205\"\n"
                    + "                                    style=\"height: 205px;border-collapse: collapse;mso-line-height-rule: exactly;\"><img\n"
                    + "                                      class=\"em_full_img\"\n"
                    + "                                      src=\"https://gallery.mailchimp.com/542fde17ee1ccbec98dd7f656/images/5c6765fc-a5bf-490b-9f7d-e073cac8257c.gif\"\n"
                    + "                                      width=\"620\" height=\"205\" alt=\"\"\n"
                    + "                                      style=\"display: block;max-width: 620px;border: 0 !important;outline: none !important;\"\n"
                    + "                                      border=\"0\">\n"
                    + "                                  </td>\n"
                    + "                                </tr>\n"
                    + "                                <tr>\n"
                    + "                                  <td class=\"em_txt1\" align=\"center\" valign=\"top\"\n"
                    + "                                    style=\"font-family: 'GT Walsheim', Poppins, Helvetica, Arial, sans-serif;font-size: 68px;line-height: 69px;color: #ffffff;font-weight: bold;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                    We’ve got<br>\n"
                    + "                                    your Email</td>\n"
                    + "                                </tr>\n"
                    + "                                <tr>\n"
                    + "                                  <td height=\"10\"\n"
                    + "                                    style=\"font-size: 1px;line-height: 1px;height: 10px;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                    &nbsp;</td>\n"
                    + "                                </tr>\n"
                    + "                                <tr>\n"
                    + "                                  <td class=\"em_txt2\" align=\"center\" valign=\"top\"\n"
                    + "                                    style=\"font-family: 'GT Walsheim', Poppins, Helvetica, Arial, sans-serif;font-size: 16px;line-height: 25px;color: #ffffff;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                    Before we get started, please take a second<br>\n"
                    + "                                    to make sure weʼve got your email right.</td>\n"
                    + "                                </tr>\n"
                    + "                                <tr>\n"
                    + "                                  <td height=\"30\"\n"
                    + "                                    style=\"height: 30px;border-collapse: collapse;mso-line-height-rule: exactly;\">&nbsp;\n"
                    + "                                  </td>\n"
                    + "                                </tr>\n"
                    + "                                <tr>\n"
                    + "                                  <td align=\"center\" valign=\"top\"\n"
                    + "                                    style=\"border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                    <table align=\"center\" width=\"200\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                      style=\"border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\">\n"
                    + "                                      <tbody>\n"
                    + "                                        <tr>\n"
                    + "                                          <td align=\"right\" valign=\"middle\" width=\"20\"\n"
                    + "                                            style=\"border-collapse: collapse;mso-line-height-rule: exactly;\"><img\n"
                    + "                                              src=\"https://gallery.mailchimp.com/542fde17ee1ccbec98dd7f656/images/4ea8f2b4-ab5e-4960-8865-3db1f25f7bd6.png\"\n"
                    + "                                              width=\"20\" height=\"40\" alt=\"\"\n"
                    + "                                              style=\"display: block;max-width: 20px;border: 0 !important;outline: none !important;\"\n"
                    + "                                              border=\"0\">\n"
                    + "                                          </td>\n"
                    + "                                          <td width=\"160\" bgcolor=\"#dcad55\" align=\"center\" valign=\"middle\"\n"
                    + "                                            style=\"font-family: 'GT Walsheim', Poppins, Helvetica, Arial, sans-serif;font-size: 13px;height: 40px;color: #ffffff;font-weight: bold;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                            <a href=" + "https://tailznet.herokuapp.com/ActivateAccount?key1=" + useremail + "&key2=" + userhash + "\n"
                    + "                                              target=\"_blank\"\n"
                    + "                                              style=\"line-height: 40px;color: #ffffff;text-decoration: none;display: block;border-collapse: collapse;mso-line-height-rule: exactly;\">CONFIRM\n"
                    + "                                              YOUR EMAIL</a>\n"
                    + "                                          </td>\n"
                    + "                                          <td align=\"left\" valign=\"middle\" width=\"20\"\n"
                    + "                                            style=\"border-collapse: collapse;mso-line-height-rule: exactly;\"><img\n"
                    + "                                              src=\"https://gallery.mailchimp.com/542fde17ee1ccbec98dd7f656/images/4dcdbe1f-f9ee-4711-ba82-297beba030d1.png\"\n"
                    + "                                              width=\"20\" height=\"40\" alt=\"\"\n"
                    + "                                              style=\"display: block;max-width: 20px;border: 0 !important;outline: none !important;\"\n"
                    + "                                              border=\"0\">\n"
                    + "                                          </td>\n"
                    + "                                        </tr>\n"
                    + "                                      </tbody>\n"
                    + "                                    </table>\n"
                    + "                                  </td>\n"
                    + "                                </tr>\n"
                    + "                              </tbody>\n"
                    + "                            </table>\n"
                    + "                          </td>\n"
                    + "                          <td width=\"90\" class=\"em_side\"\n"
                    + "                            style=\"width: 90px;border-collapse: collapse;mso-line-height-rule: exactly;\">&nbsp;</td>\n"
                    + "                        </tr>\n"
                    + "                      </tbody>\n"
                    + "                    </table>\n"
                    + "                    <!--[if gte mso 9]>\n"
                    + "                  </v:textbox>\n"
                    + "                </v:rect>\n"
                    + "                <![endif]-->\n"
                    + "                  </td>\n"
                    + "                </tr>\n"
                    + "                <tr>\n"
                    + "                  <td align=\"center\" valign=\"top\" style=\"border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                    <table align=\"center\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                      style=\"border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\">\n"
                    + "                      <tbody>\n"
                    + "                        <tr>\n"
                    + "                          <td align=\"center\" valign=\"top\"\n"
                    + "                            style=\"border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                            <table align=\"center\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                              style=\"border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\">\n"
                    + "                              <tbody>\n"
                    + "                                <tr>\n"
                    + "                                  <td width=\"140\" class=\"em_side\"\n"
                    + "                                    style=\"width: 140px;border-collapse: collapse;mso-line-height-rule: exactly;\">&nbsp;\n"
                    + "                                  </td>\n"
                    + "                                  <td align=\"center\" valign=\"top\"\n"
                    + "                                    style=\"border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                    <table align=\"center\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                      style=\"border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\">\n"
                    + "                                      <tbody>\n"
                    + "                                        <tr>\n"
                    + "                                          <td height=\"40\"\n"
                    + "                                            style=\"height: 40px;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                            &nbsp;</td>\n"
                    + "                                        </tr>\n"
                    + "\n"
                    + "                                      </tbody>\n"
                    + "                                    </table>\n"
                    + "                                  </td>\n"
                    + "                                  <td width=\"140\" class=\"em_side\"\n"
                    + "                                    style=\"width: 140px;border-collapse: collapse;mso-line-height-rule: exactly;\">&nbsp;\n"
                    + "                                  </td>\n"
                    + "                                </tr>\n"
                    + "                              </tbody>\n"
                    + "                            </table>\n"
                    + "                          </td>\n"
                    + "                        </tr>\n"
                    + "                        <tr>\n"
                    + "                          <td align=\"center\" valign=\"top\"\n"
                    + "                            style=\"border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                            <table align=\"center\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                              style=\"border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\">\n"
                    + "                              <tbody>\n"
                    + "                                <tr>\n"
                    + "                                  <td width=\"90\" class=\"em_side\"\n"
                    + "                                    style=\"width: 90px;border-collapse: collapse;mso-line-height-rule: exactly;\">&nbsp;\n"
                    + "                                  </td>\n"
                    + "                                  <td align=\"center\" valign=\"top\"\n"
                    + "                                    style=\"border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                    <table align=\"center\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"\n"
                    + "                                      style=\"border-collapse: collapse;mso-table-lspace: 0;mso-table-rspace: 0;\">\n"
                    + "                                      <tbody>\n"
                    + "                                        <tr>\n"
                    + "                                          <td height=\"30\"\n"
                    + "                                            style=\"height: 30px;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                            &nbsp;</td>\n"
                    + "                                        </tr>\n"
                    + "                                        <tr>\n"
                    + "                                          <td class=\"em_footer\" align=\"center\" valign=\"top\"\n"
                    + "                                            style=\"font-family: 'GT Walsheim', Poppins, Helvetica, Arial, sans-serif;font-size: 11px;line-height: 15px;color: #6b6b6b;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                            Tailz | its a small social network made by Vidura Fernando from Scratch<br>\n"
                    + "                                            <br>\n"
                    + "                                            Its cool and simple\n"
                    + "                                            <br>\n"
                    + "                                            I guess.</td>\n"
                    + "                                        </tr>\n"
                    + "                                        <tr>\n"
                    + "                                          <td height=\"30\"\n"
                    + "                                            style=\"height: 30px;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                            &nbsp;</td>\n"
                    + "                                        </tr>\n"
                    + "\n"
                    + "                                        <tr>\n"
                    + "                                          <td height=\"30\"\n"
                    + "                                            style=\"height: 30px;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                                            &nbsp;</td>\n"
                    + "                                        </tr>\n"
                    + "                                      </tbody>\n"
                    + "                                    </table>\n"
                    + "                                  </td>\n"
                    + "                                  <td width=\"90\" class=\"em_side\"\n"
                    + "                                    style=\"width: 90px;border-collapse: collapse;mso-line-height-rule: exactly;\">&nbsp;\n"
                    + "                                  </td>\n"
                    + "                                </tr>\n"
                    + "                              </tbody>\n"
                    + "                            </table>\n"
                    + "                          </td>\n"
                    + "                        </tr>\n"
                    + "                      </tbody>\n"
                    + "                    </table>\n"
                    + "                  </td>\n"
                    + "                </tr>\n"
                    + "                <tr>\n"
                    + "                  <td class=\"em_hide\"\n"
                    + "                    style=\"line-height: 1px;min-width: 800px;background-color: #000000;border-collapse: collapse;mso-line-height-rule: exactly;\">\n"
                    + "                    <img alt=\"\"\n"
                    + "                      src=\"https://gallery.mailchimp.com/542fde17ee1ccbec98dd7f656/images/8362e640-0caf-4a4f-a0e6-5eb28b3c2607.gif\"\n"
                    + "                      height=\"1\" width=\"800\"\n"
                    + "                      style=\"max-height: 1px;min-height: 1px;display: block;width: 800px;min-width: 800px;border: 0 !important;outline: none !important;\"\n"
                    + "                      border=\"0\">\n"
                    + "                  </td>\n"
                    + "                </tr>\n"
                    + "              </tbody>\n"
                    + "            </table>\n"
                    + "          </td>\n"
                    + "        </tr>\n"
                    + "      </tbody>\n"
                    + "    </table>\n"
                    + "    <div class=\"em_hide\" style=\"white-space:nowrap;display:none;font-size:0px;line-height:0px;\">&nbsp; &nbsp; &nbsp;\n"
                    + "      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</div>\n"
                    + "\n"
                    + "\n"
                    + "  </body>\n"
                    + "\n"
                    + "\n"
                    + "\n"
                    + "</body>\n"
                    + "\n"
                    + "</html>";

            htmlPart.setContent(html, "text/html");

            mp.addBodyPart(htmlPart);
            message.setContent(mp);
            Transport.send(message);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
